/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package birthday_kata

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class AppTest : StringSpec({
    "app has a greeting" {
        val classUnderTest = App()
        classUnderTest.greeting shouldBe "Hello World!"
    }
})
