/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package birthday_kata

import io.kotest.assertions.arrow.core.shouldBeRight
import io.kotest.core.spec.style.StringSpec

class EmailTest : StringSpec({
    "Should generate no emails if there are no employees" {
        Given()
            .`No employees`()
            .`when birthday emails are sent for today`()
            .shouldBeRight(emptyList())
    }
})
